for f in nofile1 nofile2; do cat "$f" 2>/dev/null; done; echo "rc=$?"
for f in a; do false; done; echo "rc=$?"
for f in a; do true; done; echo "rc=$?"
while false; do :; done; echo "rc=$?"
i=0; while [ $i -lt 2 ]; do i=$((i+1)); false; done; echo "rc=$?"
until true; do :; done; echo "rc=$?"
for ((i=0;i<2;i++)); do false; done; echo "rc=$?"
for f in a b; do false; break; done; echo "rc=$?"
for f in; do false; done; echo "rc=$?"
